export const routes = {
    loginUrl: '/auth/login',
    registerUrl: '/auth/register',
    resetPasswordUrl: '/auth/reset-password',
    verifyEmailUrl: '/auth/verify-email',
    homeUrl: '/',
    meUrl: '/user/me',
    changePasswordUrl: '/user/change-password',
    dashboardUrl: '/dashboard/',
    sliderUrl: '/dashboard/slider',
    editSliderUrl: '/dashboard/slider/edit',
    addSliderUrl: '/dashboard/slider/add',
    blogUrl: '/dashboard/blog',
    addBlogUrl: '/dashboard/blog/add',
    editBlogUrl: '/dashboard/blog/edit',
    usersUrl: '/dashboard/users',
    addUserUrl: '/dashboard/users/add',
};
